export const API_ERROR_CODE = {
  NETWORK_REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',
  REQUEST_FAILED: 'REQUEST_FAILED',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
