export const CLOUDINARY_UPLOAD_ERROR_CODE = {
  CLOUD_NAME_MISSING: 'CLOUD_NAME_MISSING',
  INVALID_IMAGE_TYPE: 'INVALID_IMAGE_TYPE',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  SIGNATURE_REQUEST_FAILED: 'SIGNATURE_REQUEST_FAILED',
  SIGNATURE_RESPONSE_INVALID: 'SIGNATURE_RESPONSE_INVALID',
  UPLOAD_REQUEST_FAILED: 'UPLOAD_REQUEST_FAILED',
  UPLOAD_RESPONSE_INVALID: 'UPLOAD_RESPONSE_INVALID',
  PRODUCT_CATEGORY_NOT_FOUND: 'PRODUCT_CATEGORY_NOT_FOUND',
  PRODUCT_COLOR_NOT_FOUND: 'PRODUCT_COLOR_NOT_FOUND',
  HERO_TYPE_NOT_FOUND: 'HERO_TYPE_NOT_FOUND',
  HERO_TYPE_UNSUPPORTED: 'HERO_TYPE_UNSUPPORTED',
  REVIEW_ORDER_ITEM_NOT_FOUND: 'REVIEW_ORDER_ITEM_NOT_FOUND',
  CLOUDINARY_CONFIG_MISSING: 'CLOUDINARY_CONFIG_MISSING',
  CLOUDINARY_UPLOAD_PRESET_MISSING: 'CLOUDINARY_UPLOAD_PRESET_MISSING',
} as const;

export type CloudinaryUploadErrorCode =
  (typeof CLOUDINARY_UPLOAD_ERROR_CODE)[keyof typeof CLOUDINARY_UPLOAD_ERROR_CODE];
